# Generated by Django 5.2.7 on 2025-10-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('event_date', models.DateField()),
                ('client_name', models.CharField(max_length=100)),
                ('hall', models.CharField(choices=[('Rose', 'Rose'), ('Jasmine', 'Jasmine'), ('Tulip', 'Tulip')], max_length=20)),
                ('time_slot', models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('event_type', models.CharField(choices=[('Mendi', 'Mendi'), ('Barat', 'Barat'), ('Walima', 'Walima')], max_length=20)),
                ('guests', models.PositiveIntegerField()),
                ('menu', models.CharField(max_length=200)),
            ],
        ),
    ]
