# Generated by Django 5.2.7 on 2025-10-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
