# Generated by Django 5.2.7 on 2025-10-31 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0002_alter_event_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dj_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spotlight_count', models.PositiveIntegerField(default=0)),
                ('spotlight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cool_fire_count', models.PositiveIntegerField(default=0)),
                ('cool_fire_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ice_pot_count', models.PositiveIntegerField(default=0)),
                ('ice_pot_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('confitte_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment_box', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decor_details', to='Events.event')),
            ],
        ),
    ]
