# Generated by Django 5.2.7 on 2025-10-31 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decor', '0001_initial'),
        ('Events', '0002_alter_event_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decor',
            old_name='comment_box',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='confitte_amount',
        ),
        migrations.AddField(
            model_name='decor',
            name='confetti_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='decor',
            name='cool_fire_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='decor',
            name='cool_fire_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decor',
            name='decor_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='decor',
            name='dj_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='decor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decor', to='Events.event'),
        ),
        migrations.AlterField(
            model_name='decor',
            name='ice_pot_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='decor',
            name='ice_pot_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decor',
            name='spotlight_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='decor',
            name='spotlight_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
