# Generated by Django 5.2.7 on 2025-11-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decor', '0002_rename_comment_box_decor_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='decor_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
