# Generated by Django 5.2.7 on 2025-11-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decor', '0003_decorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique='Ture'),
        ),
    ]
